#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2012 OpenWrt.org

START=99
STOP=10

USE_PROCD=1

LINGTI_BIN="/var/sbin/lingti"

lingti_genconfig() {
	[ -d /var/sbin ] || mkdir -p /var/sbin
	[ -f $LINGTI_BIN ] || ln -s /usr/sbin/lingti $LINGTI_BIN
}

start_service() {
	local enable
	config_load lingti
	config_get_bool enable lingti enabled
	if [ "$enable" -eq 1 ]; then
		lingti_genconfig
		procd_open_instance
		procd_set_param command "$LINGTI_BIN"
		procd_set_param respawn
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	fi
}
